version: "3.8"

services:

  redis:
    container_name: dev-redis
    image: redis:7-alpine
  
  db:
    container_name: dev-db
    image: postgres:16-alpine
    environment:
    - POSTGRES_PASSWORD=poppin_kernels
    volumes:
    - postgres_data:/var/lib/postgresql/data/

  backend:
    container_name: dev-backend
    build: ./backend
    environment:
    - MODE=prod
    - POSTGRES_PASSWORD=poppin_kernels
    - POSTGRES_HOST=db
    volumes:
      - static:/static
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis

  frontend:
    container_name: dev-frontend
    build: ./frontend
    ports:
    - 3000:3000
    depends_on:
    - backend

volumes:
  static:
  postgres_data:
